### ISSUE TITLE
Exception when using valueOfTheFieldEquals

### ISSUE THREAD

**Issue by lfbn** [deminy/behat-rest-testing#6]
Hi there,

We are having the following exception: 

`Requested data field 'responseData' not exist. (Exception)`

Shouldn't in here 
https://github.com/deminy/behat-rest-testing/blob/2b362c4d02a1e6f62cc8c930cc2f1238d1c059ba/src/RestTestingContext/RestContext.php#L54 be used instead the getResponseData method?

**Comment by deminy** [comment]
Thanks @lfbn for reporting the issue. I have fixed it and tagged a new version [3.0.2](https://github.com/deminy/behat-rest-testing/releases/tag/3.0.2) after that.
